
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cnat.awkshwayrd.dev
  resources:
  - ats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnat.awkshwayrd.dev
  resources:
  - ats/status
  verbs:
  - get
  - patch
  - update
